# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pseudo: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param pseudo: The pseudo of this InlineResponse200.  # noqa: E501
        :type pseudo: str
        """
        self.swagger_types = {
            'pseudo': str
        }

        self.attribute_map = {
            'pseudo': 'pseudo'
        }
        self._pseudo = pseudo

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pseudo(self) -> str:
        """Gets the pseudo of this InlineResponse200.


        :return: The pseudo of this InlineResponse200.
        :rtype: str
        """
        return self._pseudo

    @pseudo.setter
    def pseudo(self, pseudo: str):
        """Sets the pseudo of this InlineResponse200.


        :param pseudo: The pseudo of this InlineResponse200.
        :type pseudo: str
        """

        self._pseudo = pseudo
