# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tags: str=None, pseudo: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param tags: The tags of this InlineResponse2001.  # noqa: E501
        :type tags: str
        :param pseudo: The pseudo of this InlineResponse2001.  # noqa: E501
        :type pseudo: str
        """
        self.swagger_types = {
            'tags': str,
            'pseudo': str
        }

        self.attribute_map = {
            'tags': 'tags',
            'pseudo': 'pseudo'
        }
        self._tags = tags
        self._pseudo = pseudo

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tags(self) -> str:
        """Gets the tags of this InlineResponse2001.


        :return: The tags of this InlineResponse2001.
        :rtype: str
        """
        return self._tags

    @tags.setter
    def tags(self, tags: str):
        """Sets the tags of this InlineResponse2001.


        :param tags: The tags of this InlineResponse2001.
        :type tags: str
        """

        self._tags = tags

    @property
    def pseudo(self) -> str:
        """Gets the pseudo of this InlineResponse2001.


        :return: The pseudo of this InlineResponse2001.
        :rtype: str
        """
        return self._pseudo

    @pseudo.setter
    def pseudo(self, pseudo: str):
        """Sets the pseudo of this InlineResponse2001.


        :param pseudo: The pseudo of this InlineResponse2001.
        :type pseudo: str
        """

        self._pseudo = pseudo
